modLoader="javafml"
loaderVersion = "[${forge},)"
license="GNU LGPL 3.0"
issueTrackerURL="https://github.com/null822/sol_valheim"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${display_name}"
authors = "Txni, null8"
description = '''
'''
logoFile = "icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"